h = "  Happy Programming! "
print(len(h))
print(h.count("p"))
print(h.upper())
print(h.lower())
print(h.strip())
print(h.replace("Happy", "Funny"))
print(h.find("ap"))
print(h.rfind("a"))
print(h.find("zoo"))
